name: "Lokalise File Upload"

on:
  workflow_dispatch:
    inputs:
      token:
        description: "Your CLI/API token for Lokalise"
        required: true
      project-id:
        description: "Your project ID for Lokalise"
        required: true
      file-path:
        description: "The path to the file you want to upload to Lokalise"
        required: true
      language-iso:
        description: "The language code for the file you are uploading"
        required: true
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload file to Lokalise
        run: |
         chmod +x ./scripts/upload.sh
         ./scripts/upload.sh ${{ inputs.token }} ${{ inputs.project-id }} ${{ inputs.file-path }} ${{ inputs.language-iso }}
        shell: bash
       
    
